// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QL_KT_xa_sin_vien.Models;

#nullable disable

namespace QL_KT_xa_sin_vien.Migrations
{
    [DbContext(typeof(QLSinhVienContext))]
    [Migration("20260421101953_lan5")]
    partial class lan5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.DonGia", b =>
                {
                    b.Property<string>("MaDonGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maDonGia");

                    b.Property<decimal?>("DienUsageDefault")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("dienUsageDefault");

                    b.Property<decimal?>("DonGiaDien")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("donGiaDien");

                    b.Property<decimal?>("DonGiaNuoc")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("donGiaNuoc");

                    b.Property<decimal?>("DonGiaPhong")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("donGiaPhong");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayHieuLuc");

                    b.Property<decimal?>("NuocUsageDefault")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("nuocUsageDefault");

                    b.HasKey("MaDonGia");

                    b.ToTable("DonGia", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.Giuong", b =>
                {
                    b.Property<string>("MaGiuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maGiuong");

                    b.Property<string>("MaPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maPhong");

                    b.Property<string>("OccupiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("occupiedBy");

                    b.Property<string>("SoGiuong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("soGiuong");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaGiuong");

                    b.HasIndex("MaPhong");

                    b.HasIndex("OccupiedBy");

                    b.ToTable("Giuong", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maHoaDon");

                    b.Property<string>("MaHopDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maHopDong");

                    b.Property<string>("MaSv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maSV");

                    b.Property<DateTime?>("NgayXuat")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayXuat");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("soTien");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaSv");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.HopDong", b =>
                {
                    b.Property<string>("MaHopDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maHopDong");

                    b.Property<string>("Agree")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DieuKhoan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dieuKhoan");

                    b.Property<string>("DieuKhoanPdf")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaGiuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maGiuong");

                    b.Property<string>("MaPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maPhong");

                    b.Property<string>("MaSv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maSV");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngayBatDau");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngayKetThuc");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaGiuong");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaSv");

                    b.ToTable("HopDong", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.NhatKy", b =>
                {
                    b.Property<string>("MaLog")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maLog");

                    b.Property<string>("DoiTuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("doiTuong");

                    b.Property<string>("GiaTriSau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("giaTriSau");

                    b.Property<string>("GiaTriTruoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("giaTriTruoc");

                    b.Property<string>("HanhDong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hanhDong");

                    b.Property<string>("NguoiThucHien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nguoiThucHien");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGian");

                    b.HasKey("MaLog");

                    b.HasIndex("NguoiThucHien");

                    b.ToTable("NhatKy", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.PhanAnh", b =>
                {
                    b.Property<string>("MaPhanAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maPhanAnh");

                    b.Property<string>("MaPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maPhong");

                    b.Property<string>("MaSv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maSV");

                    b.Property<string>("MediaPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("moTa");

                    b.Property<string>("MucDoUuTien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mucDoUuTien");

                    b.Property<string>("NguoiXuLy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nguoiXuLy");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianCapNhat");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianTao");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaPhanAnh");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaSv");

                    b.HasIndex("NguoiXuLy");

                    b.ToTable("PhanAnh", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maPhong");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gioiTinh");

                    b.Property<string>("LoaiPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loaiPhong");

                    b.Property<string>("MaToaNha")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maToaNha");

                    b.Property<int?>("SoLuongDangO")
                        .HasColumnType("int")
                        .HasColumnName("soLuongDangO");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int")
                        .HasColumnName("sucChua");

                    b.Property<int?>("Tang")
                        .HasColumnType("int")
                        .HasColumnName("tang");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaToaNha");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maSV");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoTen");

                    b.Property<string>("Khoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("khoa");

                    b.Property<string>("Lop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lop");

                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maTaiKhoan");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoCmnd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("soCMND");

                    b.HasKey("MaSv");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maTaiKhoan");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("MatKhauMh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("matKhauMH");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenDangNhap");

                    b.Property<DateTime?>("ThoiHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vaiTro");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("VaiTro");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ_TaiKhoan_tenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.ThongBao", b =>
                {
                    b.Property<string>("MaThongBao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maThongBao");

                    b.Property<string>("LoaiThongBao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loaiThongBao");

                    b.Property<string>("NguoiGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiNhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nguoiNhan");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("noiDung");

                    b.Property<DateTime?>("ThoiGianGui")
                        .HasColumnType("datetime")
                        .HasColumnName("thoiGianGui");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaThongBao");

                    b.HasIndex("NguoiNhan");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.ToaNha", b =>
                {
                    b.Property<string>("MaToaNha")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maToaNha");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<string>("TenToaNha")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenToaNha");

                    b.HasKey("MaToaNha");

                    b.ToTable("ToaNha", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.VaiTro", b =>
                {
                    b.Property<string>("MaVaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maVaiTro");

                    b.Property<string>("QuyenHan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("quyenHan");

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenVaiTro");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.Giuong", b =>
                {
                    b.HasOne("QL_KT_xa_sin_vien.Models.Phong", "MaPhongNavigation")
                        .WithMany("Giuongs")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK_Giuong_Phong");

                    b.HasOne("QL_KT_xa_sin_vien.Models.SinhVien", "OccupiedByNavigation")
                        .WithMany("Giuongs")
                        .HasForeignKey("OccupiedBy")
                        .HasConstraintName("FK_Giuong_SinhVien");

                    b.Navigation("MaPhongNavigation");

                    b.Navigation("OccupiedByNavigation");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.HoaDon", b =>
                {
                    b.HasOne("QL_KT_xa_sin_vien.Models.HopDong", "MaHopDongNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaHopDong")
                        .HasConstraintName("FK_HoaDon_HopDong");

                    b.HasOne("QL_KT_xa_sin_vien.Models.SinhVien", "MaSvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaSv")
                        .HasConstraintName("FK_HoaDon_SinhVien");

                    b.Navigation("MaHopDongNavigation");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.HopDong", b =>
                {
                    b.HasOne("QL_KT_xa_sin_vien.Models.Giuong", "MaGiuongNavigation")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaGiuong")
                        .HasConstraintName("FK_HopDong_Giuong");

                    b.HasOne("QL_KT_xa_sin_vien.Models.Phong", "MaPhongNavigation")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK_HopDong_Phong");

                    b.HasOne("QL_KT_xa_sin_vien.Models.SinhVien", "MaSvNavigation")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaSv")
                        .HasConstraintName("FK_HopDong_SinhVien");

                    b.Navigation("MaGiuongNavigation");

                    b.Navigation("MaPhongNavigation");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.NhatKy", b =>
                {
                    b.HasOne("QL_KT_xa_sin_vien.Models.TaiKhoan", "NguoiThucHienNavigation")
                        .WithMany("NhatKies")
                        .HasForeignKey("NguoiThucHien")
                        .HasConstraintName("FK_NhatKy_TaiKhoan");

                    b.Navigation("NguoiThucHienNavigation");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.PhanAnh", b =>
                {
                    b.HasOne("QL_KT_xa_sin_vien.Models.Phong", "MaPhongNavigation")
                        .WithMany("PhanAnhs")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK_PhanAnh_Phong");

                    b.HasOne("QL_KT_xa_sin_vien.Models.SinhVien", "MaSvNavigation")
                        .WithMany("PhanAnhs")
                        .HasForeignKey("MaSv")
                        .HasConstraintName("FK_PhanAnh_SinhVien");

                    b.HasOne("QL_KT_xa_sin_vien.Models.TaiKhoan", "NguoiXuLyNavigation")
                        .WithMany("PhanAnhs")
                        .HasForeignKey("NguoiXuLy")
                        .HasConstraintName("FK_PhanAnh_TaiKhoan");

                    b.Navigation("MaPhongNavigation");

                    b.Navigation("MaSvNavigation");

                    b.Navigation("NguoiXuLyNavigation");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.Phong", b =>
                {
                    b.HasOne("QL_KT_xa_sin_vien.Models.ToaNha", "MaToaNhaNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaToaNha")
                        .HasConstraintName("FK_Phong_ToaNha");

                    b.Navigation("MaToaNhaNavigation");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.SinhVien", b =>
                {
                    b.HasOne("QL_KT_xa_sin_vien.Models.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaTaiKhoan")
                        .HasConstraintName("FK_SinhVien_TaiKhoan");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.TaiKhoan", b =>
                {
                    b.HasOne("QL_KT_xa_sin_vien.Models.VaiTro", "VaiTroNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("VaiTro")
                        .HasConstraintName("FK_TaiKhoan_VaiTro");

                    b.Navigation("VaiTroNavigation");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.ThongBao", b =>
                {
                    b.HasOne("QL_KT_xa_sin_vien.Models.TaiKhoan", "NguoiNhanNavigation")
                        .WithMany("ThongBaos")
                        .HasForeignKey("NguoiNhan")
                        .HasConstraintName("FK_ThongBao_TaiKhoan");

                    b.Navigation("NguoiNhanNavigation");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.Giuong", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.HopDong", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.Phong", b =>
                {
                    b.Navigation("Giuongs");

                    b.Navigation("HopDongs");

                    b.Navigation("PhanAnhs");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.SinhVien", b =>
                {
                    b.Navigation("Giuongs");

                    b.Navigation("HoaDons");

                    b.Navigation("HopDongs");

                    b.Navigation("PhanAnhs");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.TaiKhoan", b =>
                {
                    b.Navigation("NhatKies");

                    b.Navigation("PhanAnhs");

                    b.Navigation("SinhViens");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.ToaNha", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QL_KT_xa_sin_vien.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
